spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mybatis_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.mybatis.domain
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.example.mybatis: DEBUG
    org.mybatis: DEBUG
